"""RAG parsing, retrieval, storage, and service composition.

The package keeps the historical ``ai_agent_platform.integrations.rag`` import
surface stable while implementations live in focused modules.
"""

from ai_agent_platform.integrations.rag.errors import (
    RAGConfigurationError,
    RAGError,
    RAGProviderError,
    RAGRerankerUnavailableError,
    RAGValidationError,
)
from ai_agent_platform.integrations.rag.evaluation import (
    GradedRetrievalMetrics,
    RetrievalMetrics,
    evaluate_graded_retrieval,
    evaluate_retrieval,
)
from ai_agent_platform.integrations.rag.models import (
    DocumentChunk,
    DocumentVectorSnapshot,
    DocumentStore,
    EmbeddingProvider,
    IndexJob,
    IndexJobStore,
    IngestedDocument,
    KnowledgeDocument,
    ParsedDocument,
    RAGAnswer,
    RAGSearchResult,
    Reranker,
    RerankerCapabilities,
    RetrievedDocument,
    RetrievalExecution,
    VectorStore,
)
from ai_agent_platform.integrations.rag.factory import create_rag_service
from ai_agent_platform.integrations.rag.service import (
    ChromaVectorStore,
    GeminiEmbeddingProvider,
    HashingEmbeddingProvider,
    InMemoryVectorStore,
    NoopReranker,
    OpenAIEmbeddingProvider,
    QdrantVectorStore,
    RAGService,
    RecursiveCharacterChunker,
    SentenceTransformerEmbeddingProvider,
    SentenceTransformerCrossEncoderReranker,
    SUPPORTED_DOCUMENT_EXTENSIONS,
    SUPPORTED_TEXT_EXTENSIONS,
    TextDocumentParser,
    build_rag_prompt_messages,
)

__all__ = [
    "ChromaVectorStore",
    "DocumentChunk",
    "DocumentVectorSnapshot",
    "DocumentStore",
    "EmbeddingProvider",
    "IndexJob",
    "IndexJobStore",
    "GeminiEmbeddingProvider",
    "GradedRetrievalMetrics",
    "HashingEmbeddingProvider",
    "InMemoryVectorStore",
    "IngestedDocument",
    "KnowledgeDocument",
    "NoopReranker",
    "OpenAIEmbeddingProvider",
    "ParsedDocument",
    "QdrantVectorStore",
    "RAGAnswer",
    "RAGSearchResult",
    "RAGConfigurationError",
    "RAGError",
    "RAGProviderError",
    "RAGRerankerUnavailableError",
    "RAGService",
    "RAGValidationError",
    "RecursiveCharacterChunker",
    "Reranker",
    "RerankerCapabilities",
    "RetrievedDocument",
    "RetrievalExecution",
    "RetrievalMetrics",
    "SentenceTransformerEmbeddingProvider",
    "SentenceTransformerCrossEncoderReranker",
    "SUPPORTED_DOCUMENT_EXTENSIONS",
    "SUPPORTED_TEXT_EXTENSIONS",
    "TextDocumentParser",
    "VectorStore",
    "build_rag_prompt_messages",
    "create_rag_service",
    "evaluate_graded_retrieval",
    "evaluate_retrieval",
]
